theme: jekyll-theme-minimal
title: Visualizing Data
description: <p>Prof. <a href="georgiabullen.com">Georgia Bullen</a><br/ >gbullen2@jhu.edu<br/ >JHU Aitchison Program -- Fall 2017<br/ >Thursday, 5:30-8pm, Block 1</p>
